### ISSUE TITLE
The windows of some games (running through `winex11`) disappear after using `Alt` + `Tab`

### ISSUE THREAD

**Issue by danielfikko** [labwc/labwc#3615]
### Problem description

These games launch correctly. However, when you focus away from the game window — using `Alt` + `Tab` — to another window and then try to return to the game window, the game window disappears completely from the labwc window switcher and the waybar taskbar. ~~The game audio continues.~~

This only happens with `winex11`, i.e., xwayland. And only with these games:

GTA 3, GTA: SA, GTA: VC, M&B: W, TCSC1 and TCSC2PT.

...here is the output log reproducing the issue in these games, where the issue occurs:

[labwc-output-log-1.txt](https://github.com/user-attachments/files/28537763/labwc-output-log-1.txt)

And it does not happen with these games:

SWAT 4, SWAT 4: TSS and TCSC3CT.

...and here is the output log reproducing the issue in these games, where the issue does not occur:

[labwc-output-log-2.txt](https://github.com/user-attachments/files/28537793/labwc-output-log-2.txt)

This issue does not occur in Openbox and setting `allowAlwaysOnTop=“yes”` did not help in this case.

### Steps to reproduce

1. Run a game using `winex11` (you don't need to do anything, xwayland is already the default in Wine)
2. Press `Alt` + `Tab` to switch to another window.
3. Press `Alt` + `Tab` to switch back to the game window. This issue doesn’t occur immediately, so you’ll likely be able to switch back on your first try. However, repeat steps 2 and 3 until you can reproduce the issue.
4. Notice how the game window disappears completely.

### labwc build source

Release

### labwc version

labwc 0.20.0 (+xwayland +nls +rsvg +libsfdo) wlroots-0.20.1

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Arch Linux

**Comment by johanmalm** [comment]
@danielfikko Thanks for reporting. It this different to how it was in the `0.9.x` series? We have changed a few xwayland behaviours in the last few releases so any bisecting you could do we be gratefully received.

**Comment by danielfikko** [comment]
> [@danielfikko](https://github.com/danielfikko) Thanks for reporting. It this different to how it was in the `0.9.x` series? We have changed a few xwayland behaviours in the last few releases so any bisecting you could do we be gratefully received.

It is indeed a regression that was introduced in version `0.20.0` and is not present in version `0.9.7`. However, `git bisect` did not provide an exact commit, because some commits were not buildable.

https://github.com/labwc/labwc/commit/0c24252c85ed474cff77d508bc39a480b9993a5f
https://github.com/labwc/labwc/commit/5f8a6395a1b26b5d361092a165a98df595920d95
https://github.com/labwc/labwc/commit/48bcccddc3a0f44fb514f32edc354313cda0cb7f
https://github.com/labwc/labwc/commit/863863fc7cb43bab9fc528d4591e0b188934b765
https://github.com/labwc/labwc/commit/76f166ae42eeb875da0b8a00ec269c89eb05ec71

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
0c24252c85ed474cff77d508bc39a480b9993a5f
5f8a6395a1b26b5d361092a165a98df595920d95
48bcccddc3a0f44fb514f32edc354313cda0cb7f
863863fc7cb43bab9fc528d4591e0b188934b765
76f166ae42eeb875da0b8a00ec269c89eb05ec71
We cannot bisect more!
```

I had to run `git bisect skip` on these commits because they wouldn't build, returning the following error:

<details>
<summary>$ meson compile -C build</summary>

```
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/daniel/Public/labwc/build
ninja: Entering directory `/home/daniel/Public/labwc/build'
[14/66] Compiling C object labwc.p/src_xwayland.c.o
FAILED: [code=1] labwc.p/src_xwayland.c.o
cc -Ilabwc.p -I. -I.. -Iinclude -I../include -I/usr/include/wlroots-0.20 -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -DWLR_USE_UNSTABLE -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wunused-macros -Wshadow -Wno-unused-parameter -Wno-expansion-to-defined '-DLABWC_VERSION="0.9.5-45-g5f8a6395"' '-DGETTEXT_PACKAGE="labwc"' '-DLOCALEDIR="/usr/local/share/locale"' -pthread -MD -MQ labwc.p/src_xwayland.c.o -MF labwc.p/src_xwayland.c.o.d -o labwc.p/src_xwayland.c.o -c ../src/xwayland.c
../src/xwayland.c: In function ‘xwayland_server_init’:
../src/xwayland.c:1227:63: error: passing argument 2 of ‘wlr_xwayland_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
 1227 |                 wlr_xwayland_set_cursor(server.xwayland, image->buffer,
      |                                                          ~~~~~^~~~~~~~
      |                                                               |
      |                                                               uint8_t * {aka unsigned char *}
In file included from /usr/include/wlroots-0.20/wlr/xwayland.h:2,
                 from ../src/xwayland.c:11:
/usr/include/wlroots-0.20/wlr/xwayland/xwayland.h:288:28: note: expected ‘struct wlr_buffer *’ but argument is of type ‘uint8_t *’ {aka ‘unsigned char *’}
  288 |         struct wlr_buffer *buffer, int32_t hotspot_x, int32_t hotspot_y);
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~
../src/xwayland.c:1227:17: error: too many arguments to function ‘wlr_xwayland_set_cursor’; expected 4, have 7
 1227 |                 wlr_xwayland_set_cursor(server.xwayland, image->buffer,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
 1228 |                         image->width * 4, image->width,
 1229 |                         image->height, image->hotspot_x,
      |                         ~~~~~~~~~~~~~
/usr/include/wlroots-0.20/wlr/xwayland/xwayland.h:287:6: note: declared here
  287 | void wlr_xwayland_set_cursor(struct wlr_xwayland *wlr_xwayland,
      |      ^~~~~~~~~~~~~~~~~~~~~~~
../src/xwayland.c: In function ‘xwayland_reset_cursor’:
../src/xwayland.c:1265:63: error: passing argument 2 of ‘wlr_xwayland_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
 1265 |                 wlr_xwayland_set_cursor(server.xwayland, image->buffer,
      |                                                          ~~~~~^~~~~~~~
      |                                                               |
      |                                                               uint8_t * {aka unsigned char *}
/usr/include/wlroots-0.20/wlr/xwayland/xwayland.h:288:28: note: expected ‘struct wlr_buffer *’ but argument is of type ‘uint8_t *’ {aka ‘unsigned char *’}
  288 |         struct wlr_buffer *buffer, int32_t hotspot_x, int32_t hotspot_y);
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~
../src/xwayland.c:1265:17: error: too many arguments to function ‘wlr_xwayland_set_cursor’; expected 4, have 7
 1265 |                 wlr_xwayland_set_cursor(server.xwayland, image->buffer,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
 1266 |                         image->width * 4, image->width,
 1267 |                         image->height, image->hotspot_x,
      |                         ~~~~~~~~~~~~~
/usr/include/wlroots-0.20/wlr/xwayland/xwayland.h:287:6: note: declared here
  287 | void wlr_xwayland_set_cursor(struct wlr_xwayland *wlr_xwayland,
      |      ^~~~~~~~~~~~~~~~~~~~~~~
../src/xwayland.c:1272:28: error: ‘struct wlr_xwayland’ has no member named ‘cursor’
 1272 |         if (server.xwayland->cursor) {
      |                            ^~
In file included from ../include/common/array.h:6,
                 from ../src/xwayland.c:13:
../src/xwayland.c:1280:38: error: ‘struct wlr_xwayland’ has no member named ‘cursor’
 1280 |                 zfree(server.xwayland->cursor);
      |                                      ^~
../include/common/mem.h:66:14: note: in definition of macro ‘zfree’
   66 |         free(ptr); (ptr) = NULL; \
      |              ^~~
../src/xwayland.c:1280:38: error: ‘struct wlr_xwayland’ has no member named ‘cursor’
 1280 |                 zfree(server.xwayland->cursor);
      |                                      ^~
../include/common/mem.h:66:21: note: in definition of macro ‘zfree’
   66 |         free(ptr); (ptr) = NULL; \
      |                     ^~~
[19/66] Compiling C object labwc.p/src_config_rcxml.c.o
ninja: build stopped: subcommand failed.
```</details>

**Comment by danielfikko** [comment]
I tried reverting those commits individually, but I still run into the same issue when trying to build. I really need some help here!

**Comment by johanmalm** [comment]
> I tried reverting those commits individually, but I still run into the same issue when trying to build. I really need some help here!

When we migrate to new versions of wlroots we set the subprojects .wrap files to the exact commit, but I think you have to delete the `subprojects/wlroots` directory before re-running `meson setup build` so that the right commit is used. IIRC the is a meson command for that, but can't remember it.

**Comment by Consolatis** [comment]
Those are all wlroots chase commits. If it was working before but not after then this is likely caused by some change between wlroots 0.19.x and 0.20.x.

**Comment by danielfikko** [comment]
It really is a regression on the wlroots side.

```
48bcccddc3a0f44fb514f32edc354313cda0cb7f is the first bad commit
commit 48bcccddc3a0f44fb514f32edc354313cda0cb7f
Author: Consolatis <35009135+Consolatis@users.noreply.github.com>
Date:   Sat Jul 5 16:59:41 2025 +0200

    chase wlroots: increase wlroots meson dep

 meson.build              | 4 ++--
 subprojects/wlroots.wrap | 6 +++---
 2 files changed, 5 insertions(+), 5 deletions(-)
```

I opened an issue report at: https://gitlab.freedesktop.org/wlroots/wlroots/-/work_items/4103.

**Comment by johanmalm** [comment]
> I opened an issue report at: https://gitlab.freedesktop.org/wlroots/wlroots/-/work_items/4103.

Thanks.

Have proposed noting this in `NEWS.md`
https://github.com/labwc/labwc/pull/3624
