### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [labwc/labwc#410]
Regressed by 46ee0707901e. Defining `_POSIX_C_SOURCE` to an empty value is likely illegal. Not to be confused with `_POSIX_SOURCE` which can be empty and implies the first version aka `-D_POSIX_C_SOURCE=198808`. 
```
$ cc --version
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
```

```c
$ meson setup /tmp/labwc_build
$ meson compile -C /tmp/labwc_build
FAILED: labwc.p/src_action.c.o
cc -Ilabwc.p -I. -I../../path/to/labwc -Iinclude -Iinclude -Isubprojects/wlroots/include -Isubprojects/wlroots/include -I/usr/local/include -I/usr/local/include/libepoll-shim -I/usr/local/include/libdrm -I/usr/local/include/pixman-1 -I/usr/local/include/libxml2 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/cairo -I/usr/local/include/freetype2 -I/usr/local/include/libpng16 -I/usr/local/include/harfbuzz -I/usr/local/include/pango-1.0 -I/usr/local/include/fribidi -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wundef '-DLABWC_VERSION="0.5.0-224-g1eab4b5"' '-DGETTEXT_PACKAGE="labwc"' '-DLOCALEDIR="/usr/local/share/locale"' -pthread -D_THREAD_SAFE -MD -MQ labwc.p/src_action.c.o -MF labwc.p/src_action.c.o.d -o labwc.p/src_action.c.o -c src/action.c
In file included from src/action.c:3:
In file included from /usr/include/strings.h:34:
/usr/include/sys/cdefs.h:658:49: error: invalid token at start of a preprocessor expression
#if defined(_POSIX_C_SOURCE) && _POSIX_C_SOURCE == 1
                                                ^
/usr/include/sys/cdefs.h:664:49: error: invalid token at start of a preprocessor expression
#if defined(_POSIX_C_SOURCE) && _POSIX_C_SOURCE == 2
                                                ^
/usr/include/sys/cdefs.h:694:21: error: invalid token at start of a preprocessor expression
#if _POSIX_C_SOURCE >= 200809
                    ^
/usr/include/sys/cdefs.h:697:23: error: invalid token at start of a preprocessor expression
#elif _POSIX_C_SOURCE >= 200112
                      ^
/usr/include/sys/cdefs.h:700:23: error: invalid token at start of a preprocessor expression
#elif _POSIX_C_SOURCE >= 199506
                      ^
/usr/include/sys/cdefs.h:703:23: error: invalid token at start of a preprocessor expression
#elif _POSIX_C_SOURCE >= 199309
                      ^
/usr/include/sys/cdefs.h:706:23: error: invalid token at start of a preprocessor expression
#elif _POSIX_C_SOURCE >= 199209
                      ^
/usr/include/sys/cdefs.h:709:23: error: invalid token at start of a preprocessor expression
#elif _POSIX_C_SOURCE >= 199009
                      ^
8 errors generated.
```
See also https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_02_01_01

**Comment by jbeich** [comment]
Note, the deprecated `_POSIX_SOURCE` can indeed be defined to an empty value but then it'd try to enforce the most ancient version of POSIX.

**Comment by Consolatis** [comment]
Thanks for making us aware of this build issue. Does this fix it for FreeBSD?
```diff
diff --git a/src/action.c b/src/action.c
index 0e5d181..781e19b 100644
--- a/src/action.c
+++ b/src/action.c
@@ -1,8 +1,9 @@
 // SPDX-License-Identifier: GPL-2.0-only
-#define _POSIX_C_SOURCE
+#include <signal.h>
 #include <strings.h>
+#include <sys/types.h>
+#include <unistd.h>
 #include <wlr/util/log.h>
-#include <signal.h>
 #include "common/spawn.h"
 #include "common/zfree.h"
 #include "debug.h"
```

**Comment by jbeich** [comment]
`<sys/types.h>` can probably be dropped. According to POSIX.1-2018 `kill()` only uses `<signal.h>`. FreeBSD probably forgot to update the manpage when the header was made self-contained and DragonFly inherited that.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/kill.html
https://man.netbsd.org/kill.2
https://man.openbsd.org/kill.2
https://man.freebsd.org/kill/2
https://man.dragonflybsd.org/?command=kill&section=2

**Comment by Consolatis** [comment]
We are also using `getpid()` here, `man 2 getpid` shows the Linux docs for me and mentions both, `<sys/types.h>` and `<unistd.h>`, same for `kill()` with `<sys/types.h>` and `<signal.h>`.

`man 3 getpid` and `man 3 kill` instead show the Posix docs for me and indeed only mention `<unistd.h>` and `<signal.h>`.
Tried a clean buld without `<sys/types.h>` and it was working fine so I am tempted to indeed remove that one.

Makes me wonder if we could somehow add FreeBSD and Void Linux to the CI, together with the existing Arch container.
Guess for FreeBSD it would have to be a VM instead of a container.

**Comment by jbeich** [comment]
Old POSIX versions indeed required `<sys/types.h>`. If POSIX version is not specified most libc assume something more modern e.g.,`200809L`.

https://pubs.opengroup.org/onlinepubs/7908799/xsh/kill.html

> Guess for FreeBSD it would have to be a VM instead of a container.

CirrusCI and builds.sr.ht (maybe nonfree), TravisCI (has outdated image) support FreeBSD natively.

**Comment by Consolatis** [comment]
Other parts of the code use `#define _POSIX_C_SOURCE 200809L`

So i think the best solution would be to use that here as well and also add `<unistd.h>` (for `getpid`) together with the existing `<signal.h>` but skip the include for `<sys/types.h>`.

**Comment by johanmalm** [comment]
Sorry, my bad. Just looked at the man page again, both kill(2) and kill(3P) and it's not particularly clear. Agree that `200809L` is a  good choice if it compiles cleanly on Void.

**Comment by Consolatis** [comment]
Worked a bit on a unified build.yml for arch and void linux with musl: https://github.com/Consolatis/labwc/tree/ci/add_void_musl/.github/workflows
